[project]
name = "Papyrus"
version = "1.2.0"
description = "Papyrus Application"
authors = [
    {name = "RazorBackRoar"}
]
requires-python = ">=3.9"

[tool.setuptools.packages.find]
where = ["."]
include = ["papyrus*"]
